; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = v5

[env]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.filesystem_size = 0.5m
board = rpipico
lib_deps = 
  sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.0
  FastLED/FastLED@3.10.2
; board_build.arduino.earlephilhower.usb_vid = 0x2E8A ; rpi
; board_build.arduino.earlephilhower.usb_pid = 0x000A ; pico
board_build.arduino.earlephilhower.usb_manufacturer = "starduststorm"
board_build.arduino.earlephilhower.usb_product = "motionhexa"
; fix for memcpy_P->memcpy include issue between framework-arduinopico and SparkFun ICM 20948
extra_scripts = pre:scripts/inject_string_h.py

# Old hardware iterations:
; [env:v2]
; build_flags = -DHARDWARE_VERSION=2 -std=c++17 -DICM_20948_USE_DMP -DKISSFFT_DATATYPE=int16_t -DFIXED_POINT=1

; [env:v3]
; build_flags = -DHARDWARE_VERSION=3 -std=c++17 -DICM_20948_USE_DMP -DKISSFFT_DATATYPE=int16_t -DFIXED_POINT=1

; [env:v4]
; build_flags = -DHARDWARE_VERSION=4 -std=c++17 -DICM_20948_USE_DMP -DKISSFFT_DATATYPE=int16_t -DFIXED_POINT=1

[env:v5]  # MakerFaire 2025 hardware
build_flags = -DHARDWARE_VERSION=5 -std=c++17 -DICM_20948_USE_DMP  -DKISSFFT_DATATYPE=int16_t -DFIXED_POINT=1
