; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = v5

[env]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.filesystem_size = 0.5m
board = rpipico
lib_deps = 
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.0

# Old hardware iterations:
; [env:v2]
; build_flags = -DHARDWARE_VERSION=2 -std=c++17 -DICM_20948_USE_DMP

; [env:v3]
; build_flags = -DHARDWARE_VERSION=3 -std=c++17 -DICM_20948_USE_DMP
; lib_deps = 
; 	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.0
; 	edrean/BQ27427 Battery Fuel Gauge Arduino Library@^1.0.1

; [env:v4]
; build_flags = -DHARDWARE_VERSION=4 -std=c++17 -DICM_20948_USE_DMP
; lib_deps = 
; 	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.0
; 	edrean/BQ27427 Battery Fuel Gauge Arduino Library@^1.0.1


[env:v5]  # MakerFaire 2025 hardware
build_flags = -DHARDWARE_VERSION=5 -std=c++17 -DICM_20948_USE_DMP
lib_deps = 
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.0
	edrean/BQ27427 Battery Fuel Gauge Arduino Library@^1.0.1
